# Site
repository: vamshisiddarth/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vamshi Siddarth Gaddam
title: Senior DevOps Engineer
email: vamshisiddarth02@gmail.com
website: vamshisiddarth.github.io/resume

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: vamshisiddarth
github_username:  vamshisiddarth
stackoverflow_username: "vamshi-siddarth"
linkedin_username: https://www.linkedin.com/in/vamshi-siddarth-g-7408a718/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced Engineer with 10 years of demonstrated history in the IT industry on AWS and Azure alongside working experience on DevOps Culture leveraging multiple CI/CD tools.


  Architected and implemented multiple solutions to maintain large scale applications with High Availability and DR strategy with self healing capabilities in place by setting up monitoring(observability) with all key aspects w.r.t applications and infrastructure.

content:
  - title: Background
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Academics
        description: | # this will include new lines to allow paragraphs
          Bachelor of Technology ( B.Tech ) in Computer Science from JNTU in 2010
      - layout: left
        title: Certifications
        description: |
          - ITIL Foundation
          - AWS Certified Solutions Architect - Associate
          - Certified Kubernetes Administrator

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cloud Platforms
        description: |
          - AWS
          - Azure
          - GCP
      - layout: left
        title: Containers and Orchestration
        description: |
          - Docker
          - Docker-Compose
          - Kubernetes
          - OpenShift
      - layout: left
        title: IaC and Configurtion Management
        description: |
          - Terraform
          - Ansible
      - layout: left
        title: CI / CD
        description: |
          - GitHub Actions
          - Gitlab CI
          - DroneCI
          - Jenkins
      - layout: left
        title: Scripting / Automation
        description: |
          - Python 3.x
          - Shell
          - Batch
          - Go ( Beginner )
      - layout: left
        title: Operating Systems
        description: |
          - Linux ( RHEL / CentOS / Ubuntu )
          - Windows
      - layout: left
        title: Application Servers
        description: |
          - IBM WebSphere Application Server
          - Oracle WebLogic
          - Apache Tomcat
      - layout: left
        title: Web Servers
        description: |
          - Apache
          - Nginx
          - Caddy
      - layout: left
        title: Database
        description: |
          - Oracle
          - MySQL
          - MongoDB
          - Postgres
      - layout: left
        title: Caching and Message Queue
        description: |
          - Redis
          - Kafka
      - layout: left
        title: Additional Tools
        description: |
          - Helm
          - Prometheus Stack ( Prometheus / Grafana / AlertManager / BlackBox / Node Exporter )
          - Elastic Stack ( ElasticSearch / LogStash / Kibana / FielBeat / FluentD )
          - Datadog
          - SumoLogic

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
